version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${SECRET_KEY}

    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        environment:
            POSTGRES_PASSWORD: ${SECRET_KEY}
        depends_on: 
            - db

